# Generated by Django 5.2.17 on 2026-08-17 04:28

import datetime
import django.db.models.deletion
import django.db.models.manager
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0010_add_id_card_and_passport_numbers"),
        ("organization", "0004_seed_family_status_doc_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDailyAttendance",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(db_index=True, help_text="تاريخ التمام")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "حاضر"),
                            ("late", "متأخر"),
                            ("early_departure", "انصراف مبكر"),
                            ("excused_absence", "غياب بإذن (مخصوم)"),
                            ("unexcused_absence", "غياب بدون إذن"),
                            ("shift_off", "راحة نوبة"),
                            ("vacation", "إجازة رسمية"),
                            ("mission", "مأمورية / تكليف"),
                        ],
                        db_index=True,
                        default="present",
                        help_text="حالة التمام الفعلية",
                        max_length=30,
                    ),
                ),
                (
                    "expected_status",
                    models.CharField(
                        choices=[
                            ("duty", "واجب / خدمة"),
                            ("off", "راحة نوبة مجدولة"),
                            ("admin", "دوام إداري"),
                        ],
                        default="duty",
                        help_text="الحالة المتوقعة طبقاً لجدول النوبات",
                        max_length=20,
                    ),
                ),
                (
                    "check_in_time",
                    models.TimeField(
                        blank=True, help_text="وقت الحضور الفعلي", null=True
                    ),
                ),
                (
                    "check_out_time",
                    models.TimeField(
                        blank=True, help_text="وقت الانصراف الفعلي", null=True
                    ),
                ),
                (
                    "late_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="ساعات التأخير",
                        max_digits=5,
                    ),
                ),
                (
                    "early_departure_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="ساعات الانصراف المبكر",
                        max_digits=5,
                    ),
                ),
                (
                    "excused_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="ساعات الاستئذان أو الغياب المأذون",
                        max_digits=5,
                    ),
                ),
                (
                    "deducted_vacation_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="أيام الإجازة المخصومة من الرصيد",
                        max_digits=6,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="ملاحظات التمام أو أسباب التأخير والإذن"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="الفرد",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="members.member",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacation_transaction",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="سجل حركة الخصم المالي/الإداري من رصيد الإجازات",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="members.vacationtransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical سجل التمام اليومي",
                "verbose_name_plural": "historical سجلات التمام اليومي",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalShiftRosterGroup",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name_ar",
                    models.CharField(
                        help_text="اسم النوبة / المجموعة (مثال: نوبة أ)", max_length=100
                    ),
                ),
                ("code", models.SlugField(blank=True)),
                (
                    "pattern",
                    models.CharField(
                        choices=[
                            ("alert_24_72", "فصيل الإنذار (1 يوم عمل + 3 أيام راحة)"),
                            ("guard_24_96", "فصيل الحراسات (1 يوم عمل + 4 أيام عطلة)"),
                            ("daily_admin", "دوام إداري يومي (أحد - خميس)"),
                            ("custom", "دورة مخصصة"),
                        ],
                        default="alert_24_72",
                        max_length=30,
                    ),
                ),
                (
                    "cycle_days",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="إجمالي أيام الدورة (مثال: 4 للإنذار، 5 للحراسات)",
                    ),
                ),
                (
                    "work_days",
                    models.PositiveIntegerField(
                        default=1, help_text="عدد أيام العمل المتتالية في الدورة"
                    ),
                ),
                (
                    "rest_days",
                    models.PositiveIntegerField(
                        default=3, help_text="عدد أيام الراحة المتتالية في الدورة"
                    ),
                ),
                (
                    "anchor_date",
                    models.DateField(
                        default=datetime.date(2026, 1, 1),
                        help_text="التاريخ المرجعي لبدء الدورة",
                    ),
                ),
                (
                    "group_offset",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="إزاحة اليوم في الدورة (0 = تبدأ أول يوم، 1 = تبدأ ثاني يوم...)",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, help_text="وقت بدء الخدمة (مثال: 08:00)", null=True
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True,
                        help_text="وقت نهاية الخدمة (مثال: 08:00 لليوم التالي)",
                        null=True,
                    ),
                ),
                (
                    "shift_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=24.0,
                        help_text="إجمالي ساعات النوبة (مثال: 24.0 أو 8.0)",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "faction",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="الفصيل التابعة له هذه النوبة",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="organization.faction",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical مجموعة نوبات / وردية",
                "verbose_name_plural": "historical مجموعات النوبات والورديات",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ShiftRosterGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name_ar",
                    models.CharField(
                        help_text="اسم النوبة / المجموعة (مثال: نوبة أ)", max_length=100
                    ),
                ),
                ("code", models.SlugField(blank=True)),
                (
                    "pattern",
                    models.CharField(
                        choices=[
                            ("alert_24_72", "فصيل الإنذار (1 يوم عمل + 3 أيام راحة)"),
                            ("guard_24_96", "فصيل الحراسات (1 يوم عمل + 4 أيام عطلة)"),
                            ("daily_admin", "دوام إداري يومي (أحد - خميس)"),
                            ("custom", "دورة مخصصة"),
                        ],
                        default="alert_24_72",
                        max_length=30,
                    ),
                ),
                (
                    "cycle_days",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="إجمالي أيام الدورة (مثال: 4 للإنذار، 5 للحراسات)",
                    ),
                ),
                (
                    "work_days",
                    models.PositiveIntegerField(
                        default=1, help_text="عدد أيام العمل المتتالية في الدورة"
                    ),
                ),
                (
                    "rest_days",
                    models.PositiveIntegerField(
                        default=3, help_text="عدد أيام الراحة المتتالية في الدورة"
                    ),
                ),
                (
                    "anchor_date",
                    models.DateField(
                        default=datetime.date(2026, 1, 1),
                        help_text="التاريخ المرجعي لبدء الدورة",
                    ),
                ),
                (
                    "group_offset",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="إزاحة اليوم في الدورة (0 = تبدأ أول يوم، 1 = تبدأ ثاني يوم...)",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, help_text="وقت بدء الخدمة (مثال: 08:00)", null=True
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True,
                        help_text="وقت نهاية الخدمة (مثال: 08:00 لليوم التالي)",
                        null=True,
                    ),
                ),
                (
                    "shift_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=24.0,
                        help_text="إجمالي ساعات النوبة (مثال: 24.0 أو 8.0)",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "faction",
                    models.ForeignKey(
                        help_text="الفصيل التابعة له هذه النوبة",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_groups",
                        to="organization.faction",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        help_text="الأفراد المعينون في هذه النوبة",
                        related_name="shift_rosters",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "مجموعة نوبات / وردية",
                "verbose_name_plural": "مجموعات النوبات والورديات",
                "ordering": ["faction", "name_ar"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="DailyAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(db_index=True, help_text="تاريخ التمام")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "حاضر"),
                            ("late", "متأخر"),
                            ("early_departure", "انصراف مبكر"),
                            ("excused_absence", "غياب بإذن (مخصوم)"),
                            ("unexcused_absence", "غياب بدون إذن"),
                            ("shift_off", "راحة نوبة"),
                            ("vacation", "إجازة رسمية"),
                            ("mission", "مأمورية / تكليف"),
                        ],
                        db_index=True,
                        default="present",
                        help_text="حالة التمام الفعلية",
                        max_length=30,
                    ),
                ),
                (
                    "expected_status",
                    models.CharField(
                        choices=[
                            ("duty", "واجب / خدمة"),
                            ("off", "راحة نوبة مجدولة"),
                            ("admin", "دوام إداري"),
                        ],
                        default="duty",
                        help_text="الحالة المتوقعة طبقاً لجدول النوبات",
                        max_length=20,
                    ),
                ),
                (
                    "check_in_time",
                    models.TimeField(
                        blank=True, help_text="وقت الحضور الفعلي", null=True
                    ),
                ),
                (
                    "check_out_time",
                    models.TimeField(
                        blank=True, help_text="وقت الانصراف الفعلي", null=True
                    ),
                ),
                (
                    "late_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="ساعات التأخير",
                        max_digits=5,
                    ),
                ),
                (
                    "early_departure_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="ساعات الانصراف المبكر",
                        max_digits=5,
                    ),
                ),
                (
                    "excused_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="ساعات الاستئذان أو الغياب المأذون",
                        max_digits=5,
                    ),
                ),
                (
                    "deducted_vacation_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="أيام الإجازة المخصومة من الرصيد",
                        max_digits=6,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="ملاحظات التمام أو أسباب التأخير والإذن"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="الفرد",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="members.member",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacation_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="سجل حركة الخصم المالي/الإداري من رصيد الإجازات",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_records",
                        to="members.vacationtransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل التمام اليومي",
                "verbose_name_plural": "سجلات التمام اليومي",
                "ordering": ["-date", "member__first_name", "member__last_name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("member", "date"),
                        name="unique_active_member_daily_attendance",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
