# Generated by Django 5.2.17 on 2026-08-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("member", "Member"),
                    ("supervisor", "Supervisor"),
                ],
                default="member",
                editable=False,
                max_length=20,
            ),
        ),
    ]
