# Generated by Django 5.2.17 on 2026-08-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_phone_alter_user_user_type"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(unique=True)),
                ("name_ar", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("permissions", models.JSONField(blank=True, default=list)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("all", "الكل — جميع الفصائل"),
                            ("own_faction", "فصيله فقط"),
                            ("own_records", "السجلات التي أنشأها فقط"),
                        ],
                        default="own_faction",
                        max_length=20,
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["name_ar"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="factions",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="organization.faction"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="core.role"
            ),
        ),
    ]
