# Generated by Django 5.2.17 on 2026-08-10 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_seed_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_username", models.CharField(blank=True, max_length=150)),
                ("action", models.CharField(db_index=True, max_length=50)),
                ("target_model", models.CharField(blank=True, max_length=50)),
                ("target_id", models.CharField(blank=True, max_length=50)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BackupRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("encrypted", models.BooleanField(default=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup Record",
                "verbose_name_plural": "Backup Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledJobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("period_key", models.CharField(blank=True, max_length=20)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("success", models.BooleanField(null=True)),
                ("detail", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Scheduled Job Run",
                "verbose_name_plural": "Scheduled Job Runs",
                "ordering": ["-started_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "period_key"), name="uniq_job_run_per_period"
                    )
                ],
            },
        ),
    ]
