# Generated by Django 5.2.17 on 2026-08-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventorycategory",
            options={
                "ordering": ["name_ar"],
                "verbose_name": "تصنيف العتاد والمخزن",
                "verbose_name_plural": "تصنيفات العتاد والمخزن",
            },
        ),
        migrations.AddField(
            model_name="historicalinventoryitem",
            name="assigned_quantity",
            field=models.PositiveIntegerField(
                default=0, help_text="الكمية المسلّمة كعهدة"
            ),
        ),
        migrations.AddField(
            model_name="historicalinventoryitem",
            name="damaged_quantity",
            field=models.PositiveIntegerField(
                default=0, help_text="الكمية التالفة / المستبعدة"
            ),
        ),
        migrations.AddField(
            model_name="historicalinventoryitem",
            name="item_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="رقم الصنف أو الكود المخزني",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="historicalinventoryitem",
            name="size_spec",
            field=models.CharField(
                blank=True, help_text="المقاس / العيار / المواصفة", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="assigned_quantity",
            field=models.PositiveIntegerField(
                default=0, help_text="الكمية المسلّمة كعهدة"
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="damaged_quantity",
            field=models.PositiveIntegerField(
                default=0, help_text="الكمية التالفة / المستبعدة"
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="item_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="رقم الصنف أو الكود المخزني",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="size_spec",
            field=models.CharField(
                blank=True, help_text="المقاس / العيار / المواصفة", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="custodyrecord",
            name="action",
            field=models.CharField(
                choices=[
                    ("assigned", "تسليم عهدة"),
                    ("returned", "إرجاع عهدة"),
                    ("damaged", "تسجيل تالف / مكهن"),
                    ("maintenance", "إحالة للصيانة"),
                ],
                default="assigned",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustodyrecord",
            name="action",
            field=models.CharField(
                choices=[
                    ("assigned", "تسليم عهدة"),
                    ("returned", "إرجاع عهدة"),
                    ("damaged", "تسجيل تالف / مكهن"),
                    ("maintenance", "إحالة للصيانة"),
                ],
                default="assigned",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinventoryitem",
            name="available_quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="الكمية المتوفرة بالمستودع"
            ),
        ),
        migrations.AlterField(
            model_name="historicalinventoryitem",
            name="caliber",
            field=models.CharField(
                blank=True, help_text="العيار (إن وجد)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="historicalinventoryitem",
            name="model_name",
            field=models.CharField(
                blank=True, help_text="الموديل أو الطراز", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="historicalinventoryitem",
            name="name",
            field=models.CharField(help_text="اسم الصنف أو السلاح", max_length=150),
        ),
        migrations.AlterField(
            model_name="historicalinventoryitem",
            name="serial_number",
            field=models.CharField(
                blank=True, db_index=True, help_text="الرقم التسلسلي", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="historicalinventoryitem",
            name="total_quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="إجمالي الكمية المملوكة"
            ),
        ),
        migrations.AlterField(
            model_name="inventorycategory",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("rifle", "بندقية / سلاح خفيف"),
                    ("pistol", "مسدس"),
                    ("machine_gun", "رشاش / سلاح متوسط"),
                    ("ammo", "ذخيرة"),
                    ("armor", "عتاد وتجهيزات شخصية"),
                    ("uniform", "مهمات وملابس عسكرية"),
                    ("comm", "أجهزة اتصال ولاسلكي"),
                    ("medical", "معدات طبية وإسعاف"),
                    ("general", "مهمات ومخزن عام"),
                    ("other", "أخرى"),
                ],
                default="rifle",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="available_quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="الكمية المتوفرة بالمستودع"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="caliber",
            field=models.CharField(
                blank=True, help_text="العيار (إن وجد)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="model_name",
            field=models.CharField(
                blank=True, help_text="الموديل أو الطراز", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="name",
            field=models.CharField(help_text="اسم الصنف أو السلاح", max_length=150),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="serial_number",
            field=models.CharField(
                blank=True, db_index=True, help_text="الرقم التسلسلي", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="total_quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="إجمالي الكمية المملوكة"
            ),
        ),
    ]
