# Generated by Django 5.2.17 on 2026-08-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_alter_inventorycategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinventoryitem",
            name="domain",
            field=models.CharField(
                choices=[
                    ("armory", "قسم التسليح والأسلحة"),
                    ("inventory", "المخازن والعتاد العام"),
                ],
                db_index=True,
                default="inventory",
                help_text="نطاق الصنف (تسليح أم مخازن عامة)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inventorycategory",
            name="domain",
            field=models.CharField(
                choices=[
                    ("armory", "قسم التسليح والأسلحة"),
                    ("inventory", "المخازن والعتاد العام"),
                ],
                db_index=True,
                default="inventory",
                help_text="القسم التابع له التصنيف",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="domain",
            field=models.CharField(
                choices=[
                    ("armory", "قسم التسليح والأسلحة"),
                    ("inventory", "المخازن والعتاد العام"),
                ],
                db_index=True,
                default="inventory",
                help_text="نطاق الصنف (تسليح أم مخازن عامة)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inventorycategory",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("rifle", "بندقية / سلاح خفيف"),
                    ("pistol", "مسدس"),
                    ("machine_gun", "رشاش / سلاح متوسط"),
                    ("ammo", "ذخيرة"),
                    ("armor", "عتاد وتجهيزات شخصية"),
                    ("uniform", "مهمات وملابس عسكرية"),
                    ("comm", "أجهزة اتصال ولاسلكي"),
                    ("medical", "معدات طبية وإسعاف"),
                    ("general", "مهمات ومخزن عام"),
                    ("other", "أخرى"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
