# Generated by Django 5.2.17 on 2026-08-17 04:28

import django.db.models.deletion
import django.db.models.manager
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0002_alter_inventorycategory_options_and_more"),
        ("members", "0010_add_id_card_and_passport_numbers"),
        ("organization", "0004_seed_family_status_doc_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalVehicle",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(help_text="اسم أو طراز المركبة", max_length=150),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("patrol", "دورية / استطلاع"),
                            ("armored", "مصفحة"),
                            ("pickup", "بيك آب / دفع رباعي"),
                            ("transport", "نقل أفراد"),
                            ("truck", "شاحنة نقل / إمداد"),
                            ("ambulance", "إسعاف"),
                            ("sedan", "صالون / إدارية"),
                            ("other", "أخرى"),
                        ],
                        db_index=True,
                        default="pickup",
                        max_length=30,
                    ),
                ),
                (
                    "vin_number",
                    models.CharField(
                        db_index=True, help_text="رقم الهيكل / VIN", max_length=100
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        blank=True, db_index=True, help_text="رقم اللوحة", max_length=50
                    ),
                ),
                (
                    "model_year",
                    models.CharField(blank=True, help_text="سنة الصنع", max_length=10),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="لون المركبة", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "جاهزة للخدمة"),
                            ("maintenance", "تحت الصيانة"),
                            ("damaged", "معطلة"),
                            ("retired", "خارج الخدمة"),
                        ],
                        db_index=True,
                        default="ready",
                        max_length=20,
                    ),
                ),
                (
                    "has_weapon",
                    models.BooleanField(
                        default=False, help_text="هل تحمل المركبة سلاحاً مثبتاً؟"
                    ),
                ),
                (
                    "mounted_weapon_name",
                    models.CharField(
                        blank=True, help_text="اسم السلاح المثبت", max_length=150
                    ),
                ),
                (
                    "mounted_weapon_serial",
                    models.CharField(
                        blank=True, help_text="رقم السلاح المثبت", max_length=100
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="ملاحظات إضافية")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "assigned_driver",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="السائق أو المسؤول عن المركبة",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="members.member",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faction",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="تبعية المركبة الفصائلية",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="organization.faction",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mounted_weapon_item",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="ربط اختياري بقطعة السلاح من قسم التسليح",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="equipment.inventoryitem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "weapon_assigned_member",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="الرامي أو المسؤول عن السلاح المثبت",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="members.member",
                    ),
                ),
                (
                    "weapon_faction",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="تبعية السلاح الفصائلية",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="organization.faction",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical مركبة / آلية",
                "verbose_name_plural": "historical سجل المركبات والآليات",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(help_text="اسم أو طراز المركبة", max_length=150),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("patrol", "دورية / استطلاع"),
                            ("armored", "مصفحة"),
                            ("pickup", "بيك آب / دفع رباعي"),
                            ("transport", "نقل أفراد"),
                            ("truck", "شاحنة نقل / إمداد"),
                            ("ambulance", "إسعاف"),
                            ("sedan", "صالون / إدارية"),
                            ("other", "أخرى"),
                        ],
                        db_index=True,
                        default="pickup",
                        max_length=30,
                    ),
                ),
                (
                    "vin_number",
                    models.CharField(
                        db_index=True, help_text="رقم الهيكل / VIN", max_length=100
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        blank=True, db_index=True, help_text="رقم اللوحة", max_length=50
                    ),
                ),
                (
                    "model_year",
                    models.CharField(blank=True, help_text="سنة الصنع", max_length=10),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="لون المركبة", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "جاهزة للخدمة"),
                            ("maintenance", "تحت الصيانة"),
                            ("damaged", "معطلة"),
                            ("retired", "خارج الخدمة"),
                        ],
                        db_index=True,
                        default="ready",
                        max_length=20,
                    ),
                ),
                (
                    "has_weapon",
                    models.BooleanField(
                        default=False, help_text="هل تحمل المركبة سلاحاً مثبتاً؟"
                    ),
                ),
                (
                    "mounted_weapon_name",
                    models.CharField(
                        blank=True, help_text="اسم السلاح المثبت", max_length=150
                    ),
                ),
                (
                    "mounted_weapon_serial",
                    models.CharField(
                        blank=True, help_text="رقم السلاح المثبت", max_length=100
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="ملاحظات إضافية")),
                (
                    "assigned_driver",
                    models.ForeignKey(
                        blank=True,
                        help_text="السائق أو المسؤول عن المركبة",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_vehicles",
                        to="members.member",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faction",
                    models.ForeignKey(
                        blank=True,
                        help_text="تبعية المركبة الفصائلية",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicles",
                        to="organization.faction",
                    ),
                ),
                (
                    "mounted_weapon_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="ربط اختياري بقطعة السلاح من قسم التسليح",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mounted_on_vehicles",
                        to="equipment.inventoryitem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "weapon_assigned_member",
                    models.ForeignKey(
                        blank=True,
                        help_text="الرامي أو المسؤول عن السلاح المثبت",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_mounted_weapons",
                        to="members.member",
                    ),
                ),
                (
                    "weapon_faction",
                    models.ForeignKey(
                        blank=True,
                        help_text="تبعية السلاح الفصائلية",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mounted_weapon_vehicles",
                        to="organization.faction",
                    ),
                ),
            ],
            options={
                "verbose_name": "مركبة / آلية",
                "verbose_name_plural": "سجل المركبات والآليات",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
