# Generated by Django 5.2.17 on 2026-08-18 08:09

import django.db.models.deletion
import django.db.models.manager
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0004_seed_family_status_doc_type"),
        ("transportation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name_ar",
                    models.CharField(
                        help_text="اسم الوحدة أو الجهة الخارجية",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.SlugField(blank=True, help_text="كود أو رمز تعريفي للوحدة"),
                ),
                (
                    "commander_name",
                    models.CharField(
                        blank=True,
                        help_text="آمر الوحدة أو مسؤول التنسيق",
                        max_length=100,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="رقم هاتف التواصل", max_length=50
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="ملاحظات أو قرار الإعارة والتبعية"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="حالة النشاط"
                    ),
                ),
            ],
            options={
                "verbose_name": "وحدة / جهة خارجية",
                "verbose_name_plural": "الوحدات والجهات الخارجية",
                "ordering": ["name_ar"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="historicalvehicle",
            name="affiliation_type",
            field=models.CharField(
                choices=[
                    ("internal", "تابعة للجهاز (فصيل داخلي)"),
                    ("external", "تابعة لوحدة / جهة خارجية"),
                ],
                db_index=True,
                default="internal",
                help_text="نوع التبعية (داخلية للجهاز أو خارجية)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalvehicle",
            name="weapon_affiliation_type",
            field=models.CharField(
                choices=[
                    ("internal", "تابعة للجهاز (فصيل داخلي)"),
                    ("external", "تابعة لوحدة / جهة خارجية"),
                ],
                default="internal",
                help_text="نوع تبعية السلاح المثبت",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="affiliation_type",
            field=models.CharField(
                choices=[
                    ("internal", "تابعة للجهاز (فصيل داخلي)"),
                    ("external", "تابعة لوحدة / جهة خارجية"),
                ],
                db_index=True,
                default="internal",
                help_text="نوع التبعية (داخلية للجهاز أو خارجية)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="weapon_affiliation_type",
            field=models.CharField(
                choices=[
                    ("internal", "تابعة للجهاز (فصيل داخلي)"),
                    ("external", "تابعة لوحدة / جهة خارجية"),
                ],
                default="internal",
                help_text="نوع تبعية السلاح المثبت",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalvehicle",
            name="faction",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="تبعية المركبة الفصائلية (في حال التبعية الداخلية)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organization.faction",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="faction",
            field=models.ForeignKey(
                blank=True,
                help_text="تبعية المركبة الفصائلية (في حال التبعية الداخلية)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles",
                to="organization.faction",
            ),
        ),
        migrations.AddField(
            model_name="historicalvehicle",
            name="external_unit",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="الوحدة أو الجهة الخارجية التابعة لها المركبة بالكامل",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="transportation.externalunit",
            ),
        ),
        migrations.AddField(
            model_name="historicalvehicle",
            name="weapon_external_unit",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="الوحدة الخارجية التابع لها السلاح المثبت",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="transportation.externalunit",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="external_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="الوحدة أو الجهة الخارجية التابعة لها المركبة بالكامل",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles",
                to="transportation.externalunit",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="weapon_external_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="الوحدة الخارجية التابع لها السلاح المثبت",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mounted_weapons",
                to="transportation.externalunit",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalExternalUnit",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name_ar",
                    models.CharField(
                        db_index=True,
                        help_text="اسم الوحدة أو الجهة الخارجية",
                        max_length=150,
                    ),
                ),
                (
                    "code",
                    models.SlugField(blank=True, help_text="كود أو رمز تعريفي للوحدة"),
                ),
                (
                    "commander_name",
                    models.CharField(
                        blank=True,
                        help_text="آمر الوحدة أو مسؤول التنسيق",
                        max_length=100,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="رقم هاتف التواصل", max_length=50
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="ملاحظات أو قرار الإعارة والتبعية"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="حالة النشاط"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical وحدة / جهة خارجية",
                "verbose_name_plural": "historical الوحدات والجهات الخارجية",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
