# Generated by Django 4.2.27 on 2026-08-19 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0004_seed_family_status_doc_type"),
        ("members", "0010_add_id_card_and_passport_numbers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "transportation",
            "0002_externalunit_historicalvehicle_affiliation_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleCustodyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("assigned", "تسليم الآلية / تعيين سائق"),
                            ("returned", "إرجاع واستلام الآلية"),
                            ("maintenance", "إحالة للصيانة الفنية"),
                            ("transfer", "نقل تبعية الآلية"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                (
                    "action_date",
                    models.DateField(auto_now_add=True, help_text="تاريخ الإجراء"),
                ),
                (
                    "odometer",
                    models.PositiveIntegerField(
                        blank=True, help_text="قراءة العداد (كم)", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="ملاحظات وحالة الآلية"),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        help_text="السائق أو المسؤول عن الاستلام/الإرجاع",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_custody_records",
                        to="members.member",
                    ),
                ),
                (
                    "external_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="الوحدة الخارجية المعنية بالإجراء",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_custody_records",
                        to="transportation.externalunit",
                    ),
                ),
                (
                    "faction",
                    models.ForeignKey(
                        blank=True,
                        help_text="الفصيل المعني بالإجراء",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_custody_records",
                        to="organization.faction",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        help_text="المركبة المعنية",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custody_records",
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل حركة وحيازة الآلية",
                "verbose_name_plural": "سجلات حركة وحيازة الآليات",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalVehicleCustodyRecord",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("assigned", "تسليم الآلية / تعيين سائق"),
                            ("returned", "إرجاع واستلام الآلية"),
                            ("maintenance", "إحالة للصيانة الفنية"),
                            ("transfer", "نقل تبعية الآلية"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                (
                    "action_date",
                    models.DateField(
                        blank=True, editable=False, help_text="تاريخ الإجراء"
                    ),
                ),
                (
                    "odometer",
                    models.PositiveIntegerField(
                        blank=True, help_text="قراءة العداد (كم)", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="ملاحظات وحالة الآلية"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="السائق أو المسؤول عن الاستلام/الإرجاع",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="members.member",
                    ),
                ),
                (
                    "external_unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="الوحدة الخارجية المعنية بالإجراء",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="transportation.externalunit",
                    ),
                ),
                (
                    "faction",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="الفصيل المعني بالإجراء",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="organization.faction",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="المركبة المعنية",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical سجل حركة وحيازة الآلية",
                "verbose_name_plural": "historical سجلات حركة وحيازة الآليات",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
