# Generated by Django 4.2.27 on 2026-08-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transportation", "0003_vehiclecustodyrecord_historicalvehiclecustodyrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalvehicle",
            name="destination",
            field=models.CharField(
                blank=True,
                default="",
                help_text="وجهة التحرك / خط السير الحالي",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="historicalvehicle",
            name="purpose",
            field=models.CharField(
                blank=True,
                default="",
                help_text="الغرض من التحرك / المهمة الحالية",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="historicalvehiclecustodyrecord",
            name="destination",
            field=models.CharField(
                blank=True,
                default="",
                help_text="وجهة التحرك / خط السير",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="historicalvehiclecustodyrecord",
            name="purpose",
            field=models.CharField(
                blank=True,
                default="",
                help_text="الغرض من التحرك / المهمة",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="destination",
            field=models.CharField(
                blank=True,
                default="",
                help_text="وجهة التحرك / خط السير الحالي",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="purpose",
            field=models.CharField(
                blank=True,
                default="",
                help_text="الغرض من التحرك / المهمة الحالية",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="vehiclecustodyrecord",
            name="destination",
            field=models.CharField(
                blank=True,
                default="",
                help_text="وجهة التحرك / خط السير",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="vehiclecustodyrecord",
            name="purpose",
            field=models.CharField(
                blank=True,
                default="",
                help_text="الغرض من التحرك / المهمة",
                max_length=255,
            ),
        ),
    ]
