# Generated by Django 5.2.17 on 2026-08-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_key", models.SlugField(max_length=100, unique=True)),
                ("is_required", models.BooleanField(default=False)),
                ("is_visible", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Field Requirement",
                "verbose_name_plural": "Field Requirements",
                "ordering": ["order", "field_key"],
            },
        ),
    ]
