# Generated by Django 5.2.17 on 2026-08-10 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_historicalmemberevaluation_historicalmembernote_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentExpiryAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiry_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expiry_alerts",
                        to="members.memberdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Expiry Alert",
                "verbose_name_plural": "Document Expiry Alerts",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "expiry_date"),
                        name="uniq_expiry_alert_per_date",
                    )
                ],
            },
        ),
    ]
