# Generated by Django 5.2.17 on 2026-08-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_historicalmemberpledge_memberpledge"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmemberdocument",
            name="title",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="memberdocument",
            name="title",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
