# Generated by Django 5.2.17 on 2026-08-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_historicalmemberdocument_title_memberdocument_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmember",
            name="current_residence",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="location_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="mother_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="nearest_landmark",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="member",
            name="current_residence",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="member",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="location_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="member",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="mother_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="member",
            name="nearest_landmark",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
