# Generated by Django 5.2.17 on 2026-08-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_seed_new_field_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmember",
            name="id_card_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="passport_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="member",
            name="id_card_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="member",
            name="passport_number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
